In [55]:
import numpy as np
import pandas as pd

In [56]:
df = pd.read_excel("D:\\Downloads\\Data set for ML.xlsx")

In [57]:
df

Sr No  Supply Volage(V)  Output Frequency(GHz)  Power Dissipation(mW)  \
0       1               0.4                  0.010                 0.0098   
1       2               0.6                  0.025                 0.0114   
2       3               0.8                  0.300                 0.0123   
3       4               0.9                  0.850                 0.0142   
4       5               1.0                  1.450                 0.0156   
5       6               1.1                  3.260                 0.0178   
6       7               1.2                  5.240                 0.0190   
7       8               1.4                 10.340                 0.0213   
8       9               1.6                 15.670                 0.0226   
9      10               1.8                 20.150                 0.0247   
10     11               2.0                 24.800                 0.0265   

    Phase Noise (dBc/Hz)  
0                 -86.21  
1                 -84.73  
2                 -83.58  
3                 -82.40  
4                 -81.57  
5                 -80.56  
6                 -79.45  
7                 -78.34  
8                 -77.15  
9                 -76.43  
10                -75.86

In [58]:
df.shape

(11, 5)

In [59]:
df.head()

Sr No  Supply Volage(V)  Output Frequency(GHz)  Power Dissipation(mW)  \
0      1               0.4                  0.010                 0.0098   
1      2               0.6                  0.025                 0.0114   
2      3               0.8                  0.300                 0.0123   
3      4               0.9                  0.850                 0.0142   
4      5               1.0                  1.450                 0.0156   

   Phase Noise (dBc/Hz)  
0                -86.21  
1                -84.73  
2                -83.58  
3                -82.40  
4                -81.57

In [60]:
df.tail()

Sr No  Supply Volage(V)  Output Frequency(GHz)  Power Dissipation(mW)  \
6       7               1.2                   5.24                 0.0190   
7       8               1.4                  10.34                 0.0213   
8       9               1.6                  15.67                 0.0226   
9      10               1.8                  20.15                 0.0247   
10     11               2.0                  24.80                 0.0265   

    Phase Noise (dBc/Hz)  
6                 -79.45  
7                 -78.34  
8                 -77.15  
9                 -76.43  
10                -75.86

In [61]:
df.sample(5)

Sr No  Supply Volage(V)  Output Frequency(GHz)  Power Dissipation(mW)  \
10     11               2.0                 24.800                 0.0265   
4       5               1.0                  1.450                 0.0156   
1       2               0.6                  0.025                 0.0114   
2       3               0.8                  0.300                 0.0123   
7       8               1.4                 10.340                 0.0213   

    Phase Noise (dBc/Hz)  
10                -75.86  
4                 -81.57  
1                 -84.73  
2                 -83.58  
7                 -78.34

In [62]:
df1 = df[['Supply Volage(V)','Output Frequency(GHz)']]

In [63]:
df1

Supply Volage(V)  Output Frequency(GHz)
0                0.4                  0.010
1                0.6                  0.025
2                0.8                  0.300
3                0.9                  0.850
4                1.0                  1.450
5                1.1                  3.260
6                1.2                  5.240
7                1.4                 10.340
8                1.6                 15.670
9                1.8                 20.150
10               2.0                 24.800

In [64]:
df2 = df[['Supply Volage(V)','Power Dissipation(mW)']]

In [65]:
df2

Supply Volage(V)  Power Dissipation(mW)
0                0.4                 0.0098
1                0.6                 0.0114
2                0.8                 0.0123
3                0.9                 0.0142
4                1.0                 0.0156
5                1.1                 0.0178
6                1.2                 0.0190
7                1.4                 0.0213
8                1.6                 0.0226
9                1.8                 0.0247
10               2.0                 0.0265

In [66]:
df3 = df[['Supply Volage(V)','Phase Noise (dBc/Hz)']]

In [67]:
df3

Supply Volage(V)  Phase Noise (dBc/Hz)
0                0.4                -86.21
1                0.6                -84.73
2                0.8                -83.58
3                0.9                -82.40
4                1.0                -81.57
5                1.1                -80.56
6                1.2                -79.45
7                1.4                -78.34
8                1.6                -77.15
9                1.8                -76.43
10               2.0                -75.86

<h3 style="text-align:center;"><b>SUPPLY VOLTAGE(V) VS OUTPUT FREQUENCY(GHz)</b></h3>

In [68]:
y1 = df1[['Supply Volage(V)']]
X1 = df1[['Output Frequency(GHz)']]

In [69]:
X1

Output Frequency(GHz)
0                   0.010
1                   0.025
2                   0.300
3                   0.850
4                   1.450
5                   3.260
6                   5.240
7                  10.340
8                  15.670
9                  20.150
10                 24.800

In [70]:
y1

Supply Volage(V)
0                0.4
1                0.6
2                0.8
3                0.9
4                1.0
5                1.1
6                1.2
7                1.4
8                1.6
9                1.8
10               2.0

In [71]:
from sklearn.model_selection import train_test_split

# Split the data into training & testing sets
X1_train,X1_test,y1_train,y1_test = train_test_split(X1, y1, test_size=.30, random_state=42)

In [72]:
X1_train.shape, X1_test.shape

((7, 1), (4, 1))

In [73]:
from sklearn.linear_model import LinearRegression

# Create a Linear Regression Model
model = LinearRegression()


# Train the model using the training data
model.fit(X1_train, y1_train)

LinearRegression()

In [74]:
# Make Predictions on the test data

y1_pred = model.predict(X1_test)

In [75]:
y1_pred

array([[0.98477364],
       [0.80644711],
       [1.91152287],
       [2.16666698]])

In [76]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Calculate Evaluation Metrics

mae1 = mean_absolute_error(y1_test, y1_pred)
mse1 = mean_squared_error(y1_test, y1_pred)
r21 = r2_score(y1_test, y1_pred)

print(f"Mean Absolute Error: {mae1}")
print(f"Mean Squared Error: {mse1}")
print(f"R-Squared:{r21}")

Mean Absolute Error: 0.19996583185763023
Mean Squared Error: 0.05467290074166667
R-Squared:0.8622415099422572


<h3 style="text-align:center;"><b>POWER DISSIPATION(mW) VS Supply Volage(V)(GHz)</b></h3>

In [77]:
y2 = df2[['Power Dissipation(mW)']]
X2 = df2[['Supply Volage(V)']]

In [78]:
# Split the data into training & testing sets
X2_train,X2_test,y2_train,y2_test = train_test_split(X2, y2, test_size=.30, random_state=42)

In [79]:
# Train the model Using the Training Data
model.fit(X2_train, y2_train)

LinearRegression()

In [80]:
# Make prediction on the test data
y2_pred = model.predict(X2_test)

In [81]:
y2_pred

array([[0.01698366],
       [0.00828405],
       [0.02568327],
       [0.02816887]])

In [82]:
# Calculate evaluation metrics
mae2 = mean_absolute_error(y2_test, y2_pred)
mse2 = mean_squared_error(y2_test, y2_pred)
r2 = r2_score(y2_test, y2_pred)

print(f"Mean Absolute Error: {mae2}")
print(f"Mean Squared Error: {mse2}")
print(f"R-Sqaured:{r2}")

Mean Absolute Error: 0.001246108949416339
Mean Squared Error: 1.6791196687307823e-06
R-Sqaured:0.9611449804759741


<h3 style="text-align:center;"><b>Phase Noise (dBc/Hz) VS Supply Volage(V)</b></h3>

In [83]:
y3 = df3[['Phase Noise (dBc/Hz)']]
X3 = df3[['Supply Volage(V)']]

In [84]:
# Split the data into training & testing sets
X3_train,X3_test,y3_train,y3_test = train_test_split(X3, y3, test_size=.30, random_state=42)

In [85]:
# Train the model Using the Training Data
model.fit(X3_train, y3_train)

LinearRegression()

In [86]:
# Make prediction on the test data
y3_pred = model.predict(X3_test)

In [87]:
y3_pred

array([[-80.80389105],
       [-86.37856031],
       [-75.22922179],
       [-73.63645914]])

In [88]:
# Calculate evaluation metrics
mae3 = mean_absolute_error(y3_test, y3_pred)
mse3 = mean_squared_error(y3_test, y3_pred)
r3 = r2_score(y3_test, y3_pred)

print(f"Mean Absolute Error: {mae3}")
print(f"Mean Squared Error: {mse3}")
print(f"R-Sqaured:{r3}")

Mean Absolute Error: 0.9591926070038923
Mean Squared Error: 1.6184744178564365
R-Sqaured:0.9055474922211023
